ALTER TABLE CrewMembers
MODIFY (CREW_ROLE VARCHAR2(50) NOT NULL);

ALTER TABLE Passengers
ADD CONSTRAINT CHK_PassengerAge CHECK (PASSENGER_AGE >= 18 AND PASSENGER_AGE <= 100);

ALTER TABLE Bookings
MODIFY (BOOKING_DATE DEFAULT SYSDATE);