CREATE TABLE Passengers (
  PASSENGER_ID INTEGER PRIMARY KEY ,
  PASSENGER_NAME VARCHAR(255) NOT NULL,
  PASSENGER_PHONE VARCHAR(15) NOT NULL,
  PASSENGER_EMAIL VARCHAR(255) NOT NULL,
  PASSPORT_NUMBER VARCHAR(20),
  PASSENGER_BIRTHDATE DATE
);

CREATE TABLE Booking (
  BOOKING_ID INTEGER PRIMARY KEY,
    PASSENGER_ID INTEGER NOT NULL,
    FLIGHT_ID INTEGER NOT NULL,
    SEAT_NUMBER VARCHAR(10) NOT NULL,
    BOOKING_DATE DATE NOT NULL,
    JOURNEY_ID INTEGER NOT NULL,
    SELLER_ID INTEGER NOT NULL,
    TICKET_ID INTEGER NOT NULL,
    FOREIGN KEY (PASSENGER_ID) REFERENCES Passengers(PASSENGER_ID),
    FOREIGN KEY (FLIGHT_ID) REFERENCES Flights(FLIGHT_ID),
    FOREIGN KEY (SELLER_ID) REFERENCES TicketSellers(SELLER_ID),
    FOREIGN KEY (TICKET_ID) REFERENCES Ticket(TICKET_ID)
);

CREATE TABLE Flights (
  FLIGHT_ID INTEGER PRIMARY KEY,
    FLIGHT_NUMBER VARCHAR(100) NOT NULL,
    DEPARTURE_TIME DATE NOT NULL,
    ARRIVAL_TIME DATE NOT NULL,
    FLIGHT_STATUS VARCHAR(200) NOT NULL,
    AIRLINE_ID INTEGER NOT NULL,
    AIRCRAFT_ID INTEGER NOT NULL,
    DEPARTURE_AIRPORT INTEGER NOT NULL,
    ARRIVAL_AIRPORT INTEGER NOT NULL,
    FOREIGN KEY (AIRLINE_ID) REFERENCES Airlines(AIRLINE_ID),
    FOREIGN KEY (AIRCRAFT_ID) REFERENCES Aircraft(AIRCRAFT_ID),
    FOREIGN KEY (DEPARTURE_AIRPORT) REFERENCES Airports(AIRPORT_ID),
    FOREIGN KEY (ARRIVAL_AIRPORT) REFERENCES Airports(AIRPORT_ID)
);

CREATE TABLE Aircraft (
  AIRCRAFT_ID INTEGER PRIMARY KEY,
  AIRCRAFT_TYPE VARCHAR(200) NOT NULL,
  CAPACITY INTEGER NOT NULL
);

CREATE TABLE Airports (
  AIRPORT_ID INTEGER PRIMARY KEY,
  AIRPORT_NAME VARCHAR(200) NOT NULL,
  LOCATION VARCHAR(200) NOT NULL
);

CREATE TABLE Airlines (
  AIRLINE_ID INTEGER PRIMARY KEY,
  AIRLINE_NAME VARCHAR(200) NOT NULL,
  ORIGIN_COUNTRY VARCHAR(200) NOT NULL
);

CREATE TABLE CrewMembers (
  AIRLINE_ID INTEGER PRIMARY KEY,
  AIRLINE_NAME VARCHAR(200) NOT NULL,
  ORIGIN_COUNTRY VARCHAR(200) NOT NULL
);

CREATE TABLE WorkingCrew (
  FLIGHT_ID INTEGER NOT NULL,
  CREW_ID INTEGER NOT NULL,
  PRIMARY KEY (FLIGHT_ID, CREW_ID),
  FOREIGN KEY (FLIGHT_ID) REFERENCES Flights(FLIGHT_ID),
  FOREIGN KEY (CREW_ID) REFERENCES CrewMembers(CREW_ID)
);

CREATE TABLE Ticket (
  TICKET_ID integer PRIMARY KEY,
  TICKET_TYPE VARCHAR(255) DEFAULT 'Regular' NOT NULL,
  TICKET_PRICE FLOAT NOT NULL
);

CREATE TABLE Baggage (
  BAGGAGE_ID integer PRIMARY KEY,
  BAGGAGE_TYPE VARCHAR(255) NOT NULL,
  BAGGAGE_WEIGHT FLOAT NOT NULL,
  TICKET_ID integer NOT NULL,
  FOREIGN KEY (TICKET_ID) REFERENCES Ticket(TICKET_ID)
);

CREATE TABLE PaymentReport (
  PAYMENT_ID integer PRIMARY KEY,
  PAYMENT_DATE DATE NOT NULL,
  BOOKING_ID integer NOT NULL,
  FOREIGN KEY (BOOKING_ID) REFERENCES Booking(BOOKING_ID)
);

CREATE TABLE TicketSeller (
  SELLER_ID integer PRIMARY KEY,
  SELLER_NAME VARCHAR(255) NOT NULL,
  SELLER_CONTACT VARCHAR(255) NOT NULL
);